-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE IF NOT EXISTS pitch_accent (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 surface TEXT NOT NULL,
 reading TEXT NOT NULL,
 accent_nucleus INTEGER NOT NULL DEFAULT 0,
 mora_count INTEGER NOT NULL DEFAULT 1,
 accent_type TEXT NOT NULL DEFAULT '',
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_pitch_surface ON pitch_accent(surface);
CREATE INDEX idx_pitch_reading ON pitch_accent(reading);

ALTER TABLE pitch_accent ENABLE ROW LEVEL SECURITY;
CREATE POLICY anon_select_pitch ON pitch_accent FOR SELECT USING (true);
CREATE POLICY anon_insert_pitch ON pitch_accent FOR INSERT WITH CHECK (true);

