-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE IF NOT EXISTS analysis_history (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 input_text TEXT NOT NULL,
 result_json JSONB NOT NULL DEFAULT '{}',
 sentence_count INTEGER NOT NULL DEFAULT 0,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_history_created ON analysis_history(created_at DESC);

ALTER TABLE analysis_history ENABLE ROW LEVEL SECURITY;
CREATE POLICY anon_select_history ON analysis_history FOR SELECT USING (true);
CREATE POLICY anon_insert_history ON analysis_history FOR INSERT WITH CHECK (true);
CREATE POLICY anon_delete_history ON analysis_history FOR DELETE USING (true);

