-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE IF NOT EXISTS knowledge_points (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 point_type TEXT NOT NULL DEFAULT 'grammar',
 name TEXT NOT NULL,
 contact_count INTEGER NOT NULL DEFAULT 1,
 first_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 example_sentences JSONB NOT NULL DEFAULT '[]',
 related_history_ids UUID[] DEFAULT '{}',
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_kp_name ON knowledge_points(name);
CREATE INDEX idx_kp_type ON knowledge_points(point_type);

ALTER TABLE knowledge_points ENABLE ROW LEVEL SECURITY;
CREATE POLICY anon_select_kp ON knowledge_points FOR SELECT USING (true);
CREATE POLICY anon_insert_kp ON knowledge_points FOR INSERT WITH CHECK (true);
CREATE POLICY anon_update_kp ON knowledge_points FOR UPDATE USING (true);

