-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE IF NOT EXISTS imported_dictionaries (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 name TEXT NOT NULL,
 file_type TEXT NOT NULL CHECK (file_type IN ('pdf', 'epub')),
 entry_count INTEGER DEFAULT 0,
 status TEXT DEFAULT 'processing' CHECK (status IN ('processing', 'completed', 'failed')),
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE dictionary_entries ADD COLUMN IF NOT EXISTS source TEXT DEFAULT 'seed';
ALTER TABLE dictionary_entries ADD COLUMN IF NOT EXISTS dictionary_id UUID REFERENCES imported_dictionaries(id) ON DELETE CASCADE;

ALTER TABLE imported_dictionaries ENABLE ROW LEVEL SECURITY;
CREATE POLICY anon_select_imported_dictionaries ON imported_dictionaries FOR SELECT USING (true);
CREATE POLICY anon_insert_imported_dictionaries ON imported_dictionaries FOR INSERT WITH CHECK (true);
CREATE POLICY anon_update_imported_dictionaries ON imported_dictionaries FOR UPDATE USING (true);
CREATE POLICY anon_delete_imported_dictionaries ON imported_dictionaries FOR DELETE USING (true);

