-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE IF NOT EXISTS dictionary_entries (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 surface TEXT NOT NULL,
 reading TEXT NOT NULL,
 meanings JSONB NOT NULL DEFAULT '[]',
 pos TEXT NOT NULL DEFAULT '',
 jlpt_level INTEGER,
 is_common BOOLEAN DEFAULT false,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_dict_surface ON dictionary_entries(surface);
CREATE INDEX idx_dict_reading ON dictionary_entries(reading);

ALTER TABLE dictionary_entries ENABLE ROW LEVEL SECURITY;
CREATE POLICY anon_select_dictionary ON dictionary_entries FOR SELECT USING (true);
CREATE POLICY anon_insert_dictionary ON dictionary_entries FOR INSERT WITH CHECK (true);

