-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE IF NOT EXISTS grammar_points (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 pattern TEXT NOT NULL,
 meaning_zh TEXT NOT NULL DEFAULT '',
 meaning_en TEXT NOT NULL DEFAULT '',
 jlpt_level INTEGER NOT NULL,
 connection TEXT NOT NULL DEFAULT '',
 usage_notes TEXT NOT NULL DEFAULT '',
 examples JSONB NOT NULL DEFAULT '[]',
 tags TEXT[] DEFAULT '{}',
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_grammar_level ON grammar_points(jlpt_level);
CREATE INDEX idx_grammar_pattern ON grammar_points(pattern);

ALTER TABLE grammar_points ENABLE ROW LEVEL SECURITY;
CREATE POLICY anon_select_grammar ON grammar_points FOR SELECT USING (true);
CREATE POLICY anon_insert_grammar ON grammar_points FOR INSERT WITH CHECK (true);

