// ============================================
// 此文件由 Meoo Cloud 自动生成，请勿修改
// This file is auto-generated by Meoo Cloud, DO NOT MODIFY
// ============================================

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      analysis_history: {
        Row: {
          created_at: string
          id: string
          input_text: string
          result_json: Json
          sentence_count: number
        }
        Insert: {
          created_at?: string
          id?: string
          input_text: string
          result_json?: Json
          sentence_count?: number
        }
        Update: {
          created_at?: string
          id?: string
          input_text?: string
          result_json?: Json
          sentence_count?: number
        }
        Relationships: []
      }
      dictionary_entries: {
        Row: {
          created_at: string
          dictionary_id: string | null
          id: string
          is_common: boolean | null
          jlpt_level: number | null
          meanings: Json
          pos: string
          reading: string
          source: string | null
          surface: string
        }
        Insert: {
          created_at?: string
          dictionary_id?: string | null
          id?: string
          is_common?: boolean | null
          jlpt_level?: number | null
          meanings?: Json
          pos?: string
          reading: string
          source?: string | null
          surface: string
        }
        Update: {
          created_at?: string
          dictionary_id?: string | null
          id?: string
          is_common?: boolean | null
          jlpt_level?: number | null
          meanings?: Json
          pos?: string
          reading?: string
          source?: string | null
          surface?: string
        }
        Relationships: [
          {
            foreignKeyName: "dictionary_entries_dictionary_id_fkey"
            columns: ["dictionary_id"]
            referencedRelation: "imported_dictionaries"
            referencedColumns: ["id"]
          },
        ]
      }
      grammar_points: {
        Row: {
          connection: string
          created_at: string
          examples: Json
          id: string
          jlpt_level: number
          meaning_en: string
          meaning_zh: string
          pattern: string
          tags: string[] | null
          usage_notes: string
        }
        Insert: {
          connection?: string
          created_at?: string
          examples?: Json
          id?: string
          jlpt_level: number
          meaning_en?: string
          meaning_zh?: string
          pattern: string
          tags?: string[] | null
          usage_notes?: string
        }
        Update: {
          connection?: string
          created_at?: string
          examples?: Json
          id?: string
          jlpt_level?: number
          meaning_en?: string
          meaning_zh?: string
          pattern?: string
          tags?: string[] | null
          usage_notes?: string
        }
        Relationships: []
      }
      imported_dictionaries: {
        Row: {
          created_at: string
          entry_count: number | null
          file_type: string
          id: string
          name: string
          status: string | null
        }
        Insert: {
          created_at?: string
          entry_count?: number | null
          file_type: string
          id?: string
          name: string
          status?: string | null
        }
        Update: {
          created_at?: string
          entry_count?: number | null
          file_type?: string
          id?: string
          name?: string
          status?: string | null
        }
        Relationships: []
      }
      knowledge_points: {
        Row: {
          contact_count: number
          created_at: string
          example_sentences: Json
          first_seen_at: string
          id: string
          last_seen_at: string
          name: string
          point_type: string
          related_history_ids: string[] | null
        }
        Insert: {
          contact_count?: number
          created_at?: string
          example_sentences?: Json
          first_seen_at?: string
          id?: string
          last_seen_at?: string
          name: string
          point_type?: string
          related_history_ids?: string[] | null
        }
        Update: {
          contact_count?: number
          created_at?: string
          example_sentences?: Json
          first_seen_at?: string
          id?: string
          last_seen_at?: string
          name?: string
          point_type?: string
          related_history_ids?: string[] | null
        }
        Relationships: []
      }
      pitch_accent: {
        Row: {
          accent_nucleus: number
          accent_type: string
          created_at: string
          id: string
          mora_count: number
          reading: string
          surface: string
        }
        Insert: {
          accent_nucleus?: number
          accent_type?: string
          created_at?: string
          id?: string
          mora_count?: number
          reading: string
          surface: string
        }
        Update: {
          accent_nucleus?: number
          accent_type?: string
          created_at?: string
          id?: string
          mora_count?: number
          reading?: string
          surface?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DefaultSchema = Database[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof Database },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof (Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        Database[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof Database }
  ? (Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      Database[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof Database },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof Database }
  ? Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof Database },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof Database }
  ? Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof Database },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends { schema: keyof Database }
  ? Database[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof Database },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends { schema: keyof Database }
  ? Database[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
